[package]
name = "chat-ggml"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[dependencies]
wit-bindgen = { version = "0.25.0" }
wit-bindgen-rt = { version = "0.25.0" }
tracing-subscriber = "0.3.18"
tracing="0.1.40"
clap = { version = "4.5.16", features = ["derive"] }

[package.metadata.component]
package = "component:chat-ggml"

[package.metadata.component.target.dependencies]
"wasi:cli" = { path = "../../../wasi/wit/deps/cli" }
"wasi:io" = { path = "../../../wasi/wit/deps/io" }
"wasi:clocks" = { path = "../../../wasi/wit/deps/clocks" }
"wasi:filesystem" = { path = "../../../wasi/wit/deps/filesystem" }
"wasi:sockets" = { path = "../../../wasi/wit/deps/sockets" }
"wasi:random" = { path = "../../../wasi/wit/deps/random" }
"wasi:nn" = { path = "../../wit" }

[workspace]
